### ISSUE TITLE
Allow requirement injection in .obj.vili without Script component

### ISSUE THREAD

**Issue by Sygmei** [Sygmei/ObEngine#334]
Here, we can position the Sprite without the need of a Script
```yaml
SampleObject:
    Animator:
        path: "Sprites/SampleObject"
        default: "Idle"
    Sprite:
        rect:
            x: requirement { name: "x" }
            y: requirement { name: "y" }
            width: 1.0
            height: 1.0
            unit: "SceneUnits"
```
