### ISSUE TITLE
Named layers

### ISSUE THREAD

**Issue by Sygmei** [Sygmei/ObEngine#362]
Layers are a handy feature used to order sprites for rendering.
Currently, layers are represented as an integer value (that can be negative or positive).
The bigger the layer, the further it is in the render order (layer 2 will be displayed behind layer 1 for example).

It can easily become confusing to use when you have a lot of sprites on the screen.
A feature that could help with this are named layers.

## Named layers

Giving each layer a name could help keeping things clean, when giving a layer to a sprite you won't have to give a number anymore but a name.

```yaml
MySprite:
    rect:
        x: 0
        y: 0
        width: 1
        height: 1
    layer: "UI"
```

We could have an *optional* `layers.vili` that configures each layer : 

**As a dict**
```yaml
Debug:
    layer: -2
    visible: false # Optional field
UI:
    layer: -1
    visible: true
GameObjects:
    layer: 1
Background:
    layer: 2
```

**As a list**
```yaml
layers: [
    {name: "Debug", visible: false, layer: -2},
    "UI", # When layer is not specified and previous layers are negative, starts with 1
    "GameObjects", # Assumes layer = 2
    {name: "Background", layer: 20},
    "Underbackground" # Assumes layer = 21
]
```

- Should we use the property `layer` or `order` to define the rendering order ?
- Should the visibility be part of the layering system ? Being able to hide an entire layer is pretty useful

We need to choose between one of those options, the list one makes reordering layers easier.

## Allowing integer layers or not ?

Sometimes, when prototyping, you don't want to have to declare every layer you are gonna use.
Even worse, if you want to have dynamic layers, it makes everything worse (although you could simply use a single layer and use the [`order_in_layer`](https://github.com/Sygmei/ObEngine/issues/361) field.

Since a layer name would simply translate to an integer value we could allow direct integer values.

```yaml
FirstSprite:
    rect:
        x: 0
        y: 0
        width: 1
        height: 1
    layer: "UI"
SecondSprite:
    rect:
        x: 0
        y: 0
        width: 1
        height: 1
    layer: 3
```

## Scripting API

One of the main principles of ÖbEngine is flexibility, we don't want to force user into using configuration files if they want to use scripting instead.

We could simply have a LayerManager located into the Engine class : 

**Version 1**
```lua
Engine.Layers:setLayer("UI", -1);

local background_layer = Engine.Layers:getLayer("Background"); -- Returns an integer
print(background_layer == 20);
```

**Version 2**
```lua
Engine.Layers:setLayer("UI", -1);

local background_layer = Engine.Layers:getLayer("Background"); -- Returns a "Layer" object
print(background_layer.name, background_layer.order); -- Or background_layer.layer ? Looks confusing ?

-- Changing the order as a property ?
background_layer.order = 19;
-- Or with a method ?
background_layer:setOrder(19);
```
